name: 6000.0.46f1-standalone

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

  pull_request_target:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main

jobs:
  editor-tests:
    # Conditions:
    # 1. Allow all push runs
    # 2. Allow internal PRs (pull_request event) without label requirement
    # 3. For fork PRs (pull_request_target), require the ci-ok label
    if: github.event_name == 'push' ||
        github.event_name == 'pull_request' ||
        (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'ci-ok'))

    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '6000.0.46f1'
      testMode: 'standalone'
    secrets: inherit